name: "Terraform-prod"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  terraform:
    uses: jasonskidmore/ci-cd/.github/workflows/terraform.yaml@main
    with:
      TERRAFORM_PROJECT: project-engops-vpc
      ENV: prod
      BRANCH: prod
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
