name: "Terraform Plan Dev"
on:
  pull_request:
    branches:
      - develop

jobs:
  Plan_Dev:
    uses: jasonskidmore/terraform.ci-cd/.github/workflows/terraform.new.plan.yaml@main
    with:
      terraform_project: project-engops-vpc # terraform workspace tag/pre-fix
      env: dev
      branch: develop
      tf_version: latest                  ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      tf_vars_file: dev.auto.tfvars       ## Terraform TFVARS (Required)
      enable_TFSEC: true                ## (Optional)  Enable TFSEC IaC scans (Private repo requires GitHub enterprise)
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
