name: "Terraform-Dev-Apply"

on:
  push:
    branches:
      - develop

jobs:
  Apply_Dev:
    uses: jasonskidmore/terraform.ci-cd/.github/workflows/terraform-apply.yaml@main
    with:
      terraform_project: project-engops-vpc ## terraform workspace tag/pre-fix
      env: dev
      branch: develop
      tf_version: latest                    ## Terraform version e.g: 1.1.0 Default=latest (Optional)
      tf_vars_file: dev.auto.tfvars         ## Terraform TFVARS (Required)
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
