name: "Terraform-Develop"

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  terraform:
    env:
      TERRAFORM_PROJECT: project-engops-vpc
      ENV: dev
      BRANCH: develop
      
    uses: JasonSkidmore-Terraform/ci-cd/.github/workflows/terraform.yaml@main
    with:
      TERRAFORM_PROJECT: ${{ env.TERRAFORM_PROJECT }}
      ENV: ${{ env.ENV }}
      BRANCH: ${{ env.BRANCH }}
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
