name: "Terraform-Develop-Apply"

on:
  push:
    branches:
      - develop

jobs:
  terraform:
    uses: jasonskidmore/terraform.ci-cd/.github/workflows/terraform-apply.yaml@main
    with:
      TERRAFORM_PROJECT: project-engops-vpc
      ENV: dev
      BRANCH: develop
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
