name: "Terraform-Develop"

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  terraform:
    uses: jasonskidmore/ci-cd/.github/workflows/terraform.yaml@main
    with:
      TERRAFORM_PROJECT: project-engops-vpc
      ENV: dev
      BRANCH: develop
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
