name: "Terraform-Develop"

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop
env:
  TERRAFORM_PROJECT: project-engops-vpc
  ENV: dev
  BRANCH: develop

jobs:
  terraform:
    uses: JasonSkidmore-Terraform/ci-cd/.github/workflows/terraform/terraform.yaml
    with:
      TERRAFORM_PROJECT: $TERRAFORM_PROJECT
      ENV: $ENV
      BRANCH: $BRANCH
    secrets:
      TF_API_TOKEN: ${{ secrets.TF_API_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    # - name: Set the TERRAFORM_PROJECT
    #     id: terraform_project
    #     run: |
    #       echo "TERRAFORM_PROJECT=project-engops-vpc" >> $GITHUB_ENV
    #       echo "ENV=dev" >> $GITHUB_ENV
